kafka:
  bootstrapServers:
    - 127.0.0.1:9092
  topic: events
  numPartitions: 3
  replicationFactor: 1
  retention: "-1"
  consumerGroup: CommonProjection
  producer:
    retryMax: 10
    returnSuccess: true
    retryBackoff: 2s
    clientId: "chat-producer"
  consumer:
    returnErrors: true
    clientId: "chat-consumer"
    nackResendSleep: 100ms
    reconnectRetrySleep: 1s
    # default 1s
    offsetCommitInterval: 200ms
otlp:
  endpoint: localhost:4317
postgresql:
  url: "postgres://postgres:postgresqlPassword@localhost:5432/postgres?sslmode=disable&application_name=cqrs-app"
  maxOpenConnections: 16
  maxIdleConnections: 4
  maxLifetime: 30s
  prettyLog: true
  migration:
    migrationTable: "go_migrate"
    statementDuration: 15m
server:
  address: ":8080"
  readTimeout: "10s"
  writeTimeout: "10s"
  maxHeaderBytes: 20000000
cqrs:
  # sleepBeforeEvent: 500ms
  sleepBeforeEvent: 0
  # default 2s
  checkAreEventsProcessedInterval: 100ms
  dump: true
  import:
    file: ./events.json
  export:
    file: ./events.json
# Rest client
http:
  maxIdleConns: 2
  idleConnTimeout: '10s'
  disableCompression: false
  dump: true
